name: 'Terraform'
on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Wymagane dla WIF

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/12345/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'terraform-sa@my-project.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Setup SSH key
      #run: |
      #  echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_ed25519
      #  chmod 600 /tmp/id_ed25519

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible playbook
      run: |
        ansible-playbook pihole-setup.yml \
          -i inventory.ini \
          #--private-key /tmp/id_ed25519
      env:
        PIHOLE_PASSWORD: ${{ secrets.PIHOLE_PASSWORD }}
